---
dist: xenial
language: python
services: docker

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
  matrix:
    - TOX_ENV=centos7
    - TOX_ENV=ubuntu1804
    - TOX_ENV=debian10
    - TOX_ENV=debian9
    # check ansible version on centos7
    - TOX_ENV=ansible24-centos7
    - TOX_ENV=ansible28-centos7
    # check ansible version on debian10
    - TOX_ENV=ansible24-debian10
    - TOX_ENV=ansible28-debian10
    # check cluster consul
    - TOX_ENV=centos7-consul
    - TOX_ENV=debian10-consul
    # check swarm
    - TOX_ENV=centos7-swarm
    - TOX_ENV=debian10-swarm

matrix:
  fast_finish: true

script:
  - tox -e $TOX_ENV

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
