---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: yes
platforms:
  - name: instance-consul-master
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    exposed_ports:
      # consul-store
      - 8500/tcp
      # docker host
      - 2375/tcp
      # cluster-advertise
      - 2377/tcp
    pre_build_image: true

  - name: instance-consul-worker
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_ports:
      # docker host
      - 2375/tcp
      # cluster-advertise
      - 2377/tcp
    privileged: yes
    pre_build_image: true

provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      instance-consul-worker:
        docker_consul_enabled: yes
        docker_consul_agent: yes
        docker_consul_bind: "{{ ansible_default_ipv4.interface }}"
      instance-consul-master:
        docker_consul_enabled: yes
        docker_consul_server: no
        docker_consul_server_ui: yes

verifier:
  name: testinfra
  lint:
    name: flake8
