---
- include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}/{{ include_file }}"
        - "{{ ansible_distribution }}/{{ include_file }}"
        - "{{ ansible_os_family }}/{{ include_file }}"
        - "{{ include_file }}"
      paths:
        - 'tasks'
