---
# TODO apkawa.python
- name: Install python package
  package:
    # TODO python3
    name: python-setuptools
    state: present

- name: Add pip
  easy_install:
    name: pip

- name: 'Remove docker-py '
  pip:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-py


- name: 'Install docker python package'
  pip:
    name:
      - "docker{{ docker_python_docker_version|default('') }}"
      - "docker-compose{{ docker_python_docker_compose_version|default('') }}"
    state: present
