---

- name: Get consul bind address
  set_fact:
    docker_consul_bind_address: >-
      {%- set addr=ansible_default_ipv4.address -%}
      {%- if docker_consul_bind -%}
        {%- set addr=vars['ansible_' + docker_consul_bind].ipv4.address|default(docker_consul_bind) -%}
      {%- endif -%}
      {{ addr }}


- name: find consul store
  no_log: yes
  set_fact:
    consul_store: "{{ item.value }}"
  with_dict: "{{ hostvars }}"
  when: item.value.docker_consul_server_ui is defined and item.value.docker_consul_server_ui
  register: _store_reg

- name: Consul server ui host
  no_log: yes
  set_fact:
    docker_consul_store_host: "{{ _store_reg.results | map(attribute='ansible_facts.consul_store')| select('defined') | list | first }}"


- name: Consul join address
  set_fact:
    docker_consul_join_addr: "{{ docker_consul_join_addr|default(docker_consul_store_host.docker_consul_bind_address) }}"

- name: docker cluster daemon opts
  set_fact:
    docker_consul_daemon_opts:
      hosts: "{{ docker_cluster_hosts }}"
      cluster-advertise: "{{ docker_cluster_advertise }}"
      cluster-store: "consul://{{ docker_consul_store_address|default(docker_consul_join_addr, True) }}:8500"
      dns: ["{{ ansible_docker0 }}.ipv4.address"]

- name: Update daemon docker opts
  set_fact:
    docker_daemon_default_opts: "{{ docker_daemon_default_opts|combine(docker_consul_daemon_opts) }}"
