---

- name: find consul store
  set_fact:
    consul_store: "{{ item.value }}"
  with_dict: "{{ hostvars }}"
  when: item.value.docker_consul_store is defined and item.value.docker_consul_store
  register: _store_reg

- name: consul
  set_fact:
    docker_consul_store_host: "{{ _store_reg.results | map(attribute='ansible_facts.consul_store')| select('defined') | list | first }}"

- name: docker cluster daemon opts
  set_fact:
    docker_consul_daemon_opts:
      hosts: "{{ docker_cluster_hosts }}"
      cluster-advertise: "{{ docker_cluster_advertise }}"
      cluster-store: "{{ docker_consul_store_url|default('consul://{}:8500'.format(docker_consul_store_host.ansible_default_ipv4.address), true) }}"


- name: Update daemon docker opts
  set_fact:
    docker_daemon_default_opts: "{{ docker_daemon_default_opts|combine(docker_consul_daemon_opts) }}"
