---

- name: Start consul storage
  docker_container:
    image: progrium/consul
    name: consul-store
    hostname: consul
    command: -server -bootstrap
    restart_policy: always
    ports:
      # ui
      - 8500:8500
      # rpc
      - 8400:8400
      # dns
      - 8600:53/udp
    state: started
  when: docker_consul_store is defined and docker_consul_store

- debug: var=docker_daemon_default_opts
